### Teszt: Felhasználó létrehozása
POST http://localhost:3000/users/create-user
Content-Type: application/json

{
  "username": "csizma",
  "email": "beretizsofiaa@gmail.com",
  "domain": "csizma",
  "packageId": 2
}


### User adatok lekérése (Admin szükséges)
GET  http://localhost:3000/users
Content-Type: application/json

{
  "userId": "2a42e4d3-d6d3-4b5d-a5f2-348c3a07a223"
}

### Tárhelycsomagok lekérése
GET http://localhost:3000/packages

### Új tárhelycsomag létrehozása (Admin szükséges)
POST http://localhost:3000/packages
Content-Type: application/json

{
  "userId": "03622cb0-0c5e-418d-ab91-ad76b5327980",
  "name": "Prémium csomag",
  "price": 5000,
  "description": "Nagyobb tárhely és gyorsabb teljesítmény"
}

### Tárhelycsomag szerkesztése (Admin szükséges)
PUT http://localhost:3000/packages/4
Content-Type: application/json

{
  "userId": "2a42e4d3-d6d3-4b5d-a5f2-348c3a07a223",
  "name": "Frissített prémium csomag",
  "price": 5500,
  "description": "Még nagyobb tárhely és jobb teljesítmény"
}

### Tárhelycsomag törlése (Admin szükséges)
DELETE http://localhost:3000/packages/5
Content-Type: application/json

{
  "userId": "03622cb0-0c5e-418d-ab91-ad76b5327980"
}
